apiVersion: projects/v1
kind: Deployment
metadata:
    name: project
    namespace: default
    labels:
        project: project
spec:
    replicas: 3
    selector:
        matchLabels:
            project: project
    template:
        metadata:
            labels:
                project: project
        spec:
            containers:
                - name: project
                  image: profiteray/project:latest
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: nobel-api-service
    namespace: default
spec:
    selector:
        project: project
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    type: LoadBalancer
